language: php

php:
  - 7.4

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - php bin/phpcs --standard=PSR12 src
  - php bin/phpstan analyse src